### ISSUE TITLE
How to get image metadata (creation / modify date), like identify command

### ISSUE THREAD

**Issue by carafelix** [mmomtchev/magickwand.js#137]
First of all, great work! Really amazed at the scale of this project. 
now... What is the binding for something like `identify`? I want to extract image metadata. Thanks

**Comment by mmomtchev** [comment]
The included example does it:

https://github.com/mmomtchev/magickwand.js/blob/4bf1409322340568408f07e999dd738453f7adda/example/example.mjs#L25
