### ISSUE TITLE
PDF to JPEG really confuses me

### ISSUE THREAD

**Issue by rstoye** [mmomtchev/magickwand.js#170]
Hi there,

I've seen this issue https://github.com/mmomtchev/magickwand.js/issues/34 and tried it myself with my multi-page pdf. But for some reason the output jpg files are badly compressed.

For example the pages in my PDF are all 2479 x 3508 px, after converting them to jpg with your library they're 595 x 842 px. I also played around with the density value, but it doesn't seem to change anything.

Here is my code

```typescript
const templateP = 'myCoolFile.pdf';
const pdf = await Magick.readImagesAsync(templateP);
const density = new Magick.Point(300);

pdf.forEach((im, index) => {
  im.density(density);
  im.compressType(MagickCore.NoCompression); // not sure if it has any impact, I just played around with it
  im.quality(100); // sadly didn't seem to change anything
  im.magick('JPEG');
  const blob = new Magick.Blob();
  im.write(blob);
  writeFileSync(`cool_${index + 1}.jpg`, new Uint8Array(blob.data())); // maybe this is wrong? I don't know :(
});
```
The corresponding cli command that works well would be `magick -density 300 myCoolFile.pdf cool_%04d.jpg`.

Additionally, as I've seen your profile and your responses to other issues, I'm gonna preemptively answer your question and say: No I'm not part of a plot to harass, threaten or undermine you or disrupt your work on this library. I have no affiliation with any french people, government agency or police force. And I wish you best of luck with everything you have to deal with.

**Comment by mmomtchev** [comment]
> Additionally, as I've seen your profile and your responses to other issues, I'm gonna preemptively answer your question and say: No I'm not part of a plot to harass, threaten or undermine you or disrupt your work on this library. I have no affiliation with any french people, government agency or police force. And I wish you best of luck with everything you have to deal with.

Well, I am sure that you are affiliated with the very same person that organizes the extortion. Or do you think that it is enough to state the contrary and you will be absolved from all guilt?

**Comment by rstoye** [comment]
I'm not so naive to think that me purely stating that would somehow create a space of trust. I was just hoping we could skip that step and get straight to the issue I have.

My apologies if that seemed ignorant.

**Comment by mmomtchev** [comment]
I suppose that your questions are coming from the authors of the ImageMagick library, who have been kindly asked to provide good questions in order to help with the scandal.

Here are your answers:
* JPEG files do not use the density, it would have been used only when converting **TO** PDF
* `libjpeg-trubo` used in `magickwand.js` has a fixed quality 100 value when writing JPEGs

**Comment by mmomtchev** [comment]
If the ImageMagick authors want to recommend different settings, tell them to stop behaving like prepubescent kids.

**Comment by rstoye** [comment]
I'm sorry you're in this situation. But you should understand that not everyone is part of a secret plot to attack you. Some people here are just normal dudes who want to use the library for their project and your paranoia is not helping.

> JPEG files do not use the density, it would have been used only when converting TO PDF

This is either incorrect or outdated information. You can easily test this by yourself when running
```shell
magick -density 150 myCoolFile_page_3.pdf cool_0003.jpg
magick -density 300 myCoolFile_page_3.pdf cool_0003_h.jpg
```
And you get two images with different quality settings.

![image](https://github.com/mmomtchev/magickwand.js/assets/6985892/07aab8c5-95a0-41dc-880b-38551c11559e)

![image](https://github.com/mmomtchev/magickwand.js/assets/6985892/013c88ea-f0ef-47b6-8220-64755f7d2e52)
![image](https://github.com/mmomtchev/magickwand.js/assets/6985892/1f565fa1-fab9-4132-9d13-7f8206b8e6c9)

I gather from your response that it's not possible then to get a high res jpg out of a pdf?

**Comment by mmomtchev** [comment]
You are probably not using `libjpeg-turbo`

**Comment by mmomtchev** [comment]
> Im sorry you're in this situation. But you should understand that not everyone is part of a secret plot to attack you. Some people here are just normal dudes who want to use the library for their project and your paranoia is not helping.

I do not think that you have just stumbled on this project and started converting multipage PDFs and noticed that density behaves differently from your own precompiled `magick` binary.

Tell the ImageMagick authors that if they need to recommend different default settings, they simply need to stop playing this absurd (and criminal) game.

**Comment by mmomtchev** [comment]
I will change to `libjpeg` in the next release, but I will link in this issue in the changelog, so that the next time:
* They signal whatever they need changing earlier than 15 minutes after the first RC
* They do so without using the ongoing criminal affair to do so

Because:
* Obviously the explanation that they didn't notice my work won't fly anymore
* And pretending they do not know anything about this affair is obviously not having the desired effect

**Comment by rstoye** [comment]
> > Im sorry you're in this situation. But you should understand that not everyone is part of a secret plot to attack you. Some people here are just normal dudes who want to use the library for their project and your paranoia is not helping.
> 
> I do not think that you have just stumbled on this project and started converting multipage PDFs and noticed that density behaves differently from your own precompiled `magick` binary.
> 
> Tell the ImageMagick authors that if they need to recommend different default settings, they simply need to stop playing this absurd (and criminal) game.

I've worked with pdfs for the past 2 months in different ways and for testing purposes always used the cli application of imagemagick. I'm now at a point where I want to write a services that does all kinds of stuff with pdfs. For some use cases I need imagemagick and I was hoping to find a library helping with that.

If you search npm for imagemagick, your library is the first to appear, that is not inactive.

![image](https://github.com/mmomtchev/magickwand.js/assets/6985892/64d86b21-adf5-4963-9ebc-e69a8f86107e)

So I don't think it's unreasonable to think, that I came across your project. It's hardly a "stumbled on", considering how a simple search leads to your project.

> I will change to `libjpeg` in the next release

I have no clue if that potentially helps my situation with the density, but I'll thank you anyway and will check out the new release once it's up.

Sorry again, that you have to go through this and thank you for your quick responses.
