### ISSUE TITLE
`Magick.Image.formatMagickCaption` is unusable

### ISSUE THREAD

**Issue by jasperchan** [mmomtchev/magickwand.js#216]
It doesn't seem to be exported as part of the library.

**Comment by mmomtchev** [comment]
I don't see `Magick::Image::formatMagickCaption` in the Magick++ C++ API. There is a `FormatMagickCaption` in MagickCore - the C API. Is this what you mean? The `MagickCore` C API is only partially wrapped, as its primitives are very difficult to use from a memory-safe language such as JavaScript.

**Comment by mmomtchev** [comment]
Fixed by https://github.com/mmomtchev/magickwand.js/pull/221
