### ISSUE TITLE
How to correctly enter parameters into the distort method

### ISSUE THREAD

**Issue by presscot** [mmomtchev/magickwand.js#220]
im.distort('Perspective', 4, [
      0, 0, 0, 0,
      0, 90, 0, 90, 
      90, 0, 90, 25,
      90, 90, 90, 65,
]);

throws error "Illegal arguments for function distort"

**Comment by mmomtchev** [comment]
I still don't have automatic typemaps for C-style arrays in SWIG JSE, I have only `std::vector`. Since this is the second time somebody asks for a C-style array in the last 48h in a project where there haven't been any other issues, I guess this is a SWIG JSE feature request? 😄

**Comment by presscot** [comment]
First of all, Thanks for your answer.
To be honest, I have a quick task and I’m testing the capabilities of several libraries. I couldn’t find the documentation, and I’ve never used SWIG before. In the source code, the parameters are handled through arrays of real numbers. Unfortunately, Float64Array.buffer also doesn’t work. The interface can be anything as long as you can tell me how to use it or make it functional 😄 For now, I have to settle for executing system commands.

**Comment by mmomtchev** [comment]
So in a project that hasn't had any issues opened for the last 2 months, two persons opened issues about 2 obscure methods that use C-style arrays, but it is all random. Makes sense. Especially since the method does not accept even `Float64Array`.
