### ISSUE TITLE
Cannot use in MacOS arm64

### ISSUE THREAD

**Issue by daoanhthanh** [mmomtchev/magickwand.js#63]
I installed, imported and used like you specified in document. But when I run I got this error:

```
$> node index.js
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/thanh_da/Documents/im_nodejs/node_modules/magickwand.js/lib/binding/darwin-arm64/magickwand.node'
Require stack:
- /Users/thanh_da/Documents/im_nodejs/node_modules/magickwand.js/lib/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/thanh_da/Documents/im_nodejs/node_modules/magickwand.js/lib/index.cjs:21:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/thanh_da/Documents/im_nodejs/node_modules/magickwand.js/lib/index.cjs'
  ]
}

Node.js v20.9.0
```

This is the only code that use the lib

```nodejs
import { Magick } from "magickwand.js";

const resize = async (imageArrayBuffer, specification) => {
	const wizard = new Magick.Blob(imageArrayBuffer);
	console.log("Before transfrom", wizard.length);
	const im = new Magick.Image();
	await im.readAsync(wizard);
	return await im.resize(specification).then(() => wizard.data);
};
```

**Can someone please explain to me, is this a library error or did I do something wrong?**

This is my `package.json`

```
{
  "name": "lambda-image",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-sdk/client-s3": "^3.454.0",
    "axios": "^1.6.2",
    "file-type": "^18.7.0",
    "magickwand.js": "^1.0.0-beta.6"
  }
}
```

**Comment by mmomtchev** [comment]
As you may have seen from my profile, I am currently unemployed because of an extortion involving the French judicial system. Some of the people involved in the extortion are trying to make me shut up and they are throwing a promise for a mac arm64 into the mix. Does your posting of this issue have anything to do with this extortion?

**Comment by daoanhthanh** [comment]
> As you may have seen from my profile, I am currently unemployed because of an extortion involving the French judicial system. Some of the people involved in the extortion are trying to make me shut up and they are throwing a promise for a mac arm64 into the mix. Does your posting of this issue have anything to do with this extortion?

No, please. I'm just a normal user who finds your project interesting. I'm not from your country and know nothing about your situation. How terrible it is for a person to be caught in that situation. I considered donating to you, but the minimum amount is 2/3 of my monthly income, so I can't now donate to you.

**Comment by daoanhthanh** [comment]
@mmomtchev I know that with the current situation, it is difficult for you to continue the great unfinished work. However, if at any moment you suddenly come up with an idea for the cause of the error I mentioned above, I would appreciate it if you could share it here.

**Comment by Vovcharaa** [comment]
Hello @mmomtchev
GitHub added support for free Apple Silicon runners for GitHub Actions https://github.com/actions/runner-images/issues/9254
Could you consider providing prebuilt darwin-arm64 packages now?

**Comment by mmomtchev** [comment]
`magickwand.js@next` supports macOS `arm64`
