### ISSUE TITLE
Composite transparent images

### ISSUE THREAD

**Issue by renderappco** [mmomtchev/magickwand.js#64]
Hi there,

I just found out about your library! Many thanks for putting this together. It looks great!

I was trying to experiment a bit with overlaying multiple images together. I want to achieve a similar "alpha blend" style as photoshop, where you can overlay multiple transparent images on top of the other. I used your example and it got me here, but this is multiplying, which I don't want and also I haven't figured out how to save the resulting image, to the disk.

Any help would be more than appreciated!

```
var mw = require('node-magickwand');

const test = async () => {
    let im1 = new mw.Magick.Image("image1.png");
    let im2 = new mw.Magick.Image("image2.png");
    
    await im1.compositeAsync(im2, '0x0+0+0', mw.MagickCore.MultiplyCompositeOp);
    
    const blob = new mw.Magick.Blob;
    await im1.writeAsync(blob);
    const b64 = await blob.base64Async();
    console.log(b64);
}
test()
```

**Comment by mmomtchev** [comment]
The compositing operators are defined here: https://www.imagemagick.org/Magick++/Enumerations.html#CompositeOperator

You can use `im.write{Async}(filename)` to write the image without using a `Blob`. Or you can get the `ArrayBuffer` of the blob with `blob.data()` and write the image yourself.

**Comment by mmomtchev** [comment]
In case you haven't seen my profile, I currently live on social welfare because they are extorting me about an affair that includes high-level corruption in the French judiciary. In order to intimidate me, people are making simultaneous posts on github, yours is one of these. Do you have anything to say about this?
